# Generated by Django 4.1.3 on 2022-11-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='summary',
            field=models.TextField(help_text='Intruduce de que trata la Pelicula', max_length=300),
        ),
    ]
